---

- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat
  tags: filebeat

- name: create folder /etc/pki/tls/certs
  file: >
    path="/etc/pki/tls/certs"
    state=directory
    owner="{{ os_user }}"
    group="{{ os_user }}"
    mode=0755
  tags: filebeat

- name: Download Filebeat logzio ssl cert
  get_url:
    url: https://raw.githubusercontent.com/logzio/public-certificates/master/AAACertificateServices.crt
    dest: /etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: '0644'
  notify: restart filebeat
  tags: filebeat
